# Generated by Django 2.2.1 on 2019-06-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('college', models.CharField(choices=[('CEDAT', 'College Of Engineering Design Art ANd Technology'), ('COBAMS', 'Economics')], help_text='From the dropdown menu select your college', max_length=100)),
                ('department', models.CharField(help_text='Choose your department', max_length=100)),
                ('program', models.CharField(help_text='What is your Program', max_length=50)),
                ('year_of_study', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], help_text='Select your your of study', max_length=4)),
                ('full_name', models.CharField(help_text='Enter Your full official name', max_length=100)),
                ('reg_no', models.CharField(help_text='Enter your Registration number', max_length=20, primary_key=True, serialize=False)),
                ('student_no', models.CharField(default='', help_text='Your student number', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter your birthday', null=True)),
                ('email', models.EmailField(default='', help_text='The email will only be used for official purposes', max_length=254)),
                ('photo', models.ImageField(blank=True, default='default.jpg', help_text='This will be your profile picture', upload_to='')),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'female'), ('u', 'undefined')], default='', help_text='Sex', max_length=10)),
                ('post', models.CharField(help_text='post of leadership', max_length=100)),
                ('vote', models.BooleanField(default=False, help_text='student vote')),
            ],
        ),
    ]
