# Generated by Django 2.2.1 on 2019-06-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='The user who commented')),
                ('comment', models.TextField(verbose_name='Your comment')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20)),
                ('student_no', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('college', models.CharField(choices=[('CEDAT', 'College Of Engineering Design Art ANd Technology'), ('COBAMS', 'Economics')], help_text='From the dropdown menu select your college', max_length=100)),
                ('department', models.CharField(help_text='Choose your department', max_length=100)),
                ('program', models.CharField(help_text='What is your Program', max_length=50)),
                ('year_of_study', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], help_text='Select your your of study', max_length=4)),
                ('full_name', models.CharField(help_text='Enter Your full official name', max_length=100)),
                ('reg_no', models.CharField(help_text='Enter your Registration number', max_length=20, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter your birthday', null=True)),
                ('email', models.EmailField(default='', help_text='The email will only be used for official purposes', max_length=254)),
                ('photo', models.ImageField(blank=True, default='default.png', help_text='This will be your profile picture', upload_to='')),
                ('phone', models.CharField(default='', max_length=10)),
                ('mobile', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
