# Generated by Django 2.2.1 on 2019-06-14 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20)),
                ('student_no', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('college', models.CharField(choices=[('CEDAT', 'College Of Engineering Design Art ANd Technology'), ('COBAMS', 'Economics')], help_text='From the dropdown menu select your college', max_length=100)),
                ('department', models.CharField(help_text='Choose your department', max_length=100)),
                ('program', models.CharField(help_text='What is your Program', max_length=50)),
                ('year_of_study', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], help_text='Select your your of study', max_length=4)),
                ('full_name', models.CharField(help_text='Enter Your full official name', max_length=100)),
                ('reg_no', models.CharField(help_text='Enter your Registration number', max_length=20, primary_key=True, serialize=False)),
                ('student_no', models.CharField(default='', help_text='Your student number', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter your birthday', null=True)),
                ('email', models.EmailField(default='', help_text='The email will only be used for official purposes', max_length=254)),
                ('photo', models.ImageField(blank=True, default='default.jpg', help_text='This will be your profile picture', upload_to='')),
                ('phone', models.CharField(default='', max_length=10)),
                ('mobile', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('key', models.CharField(default='', help_text='pk1', max_length=100, primary_key=True, serialize=False)),
                ('keyComment', models.CharField(default='', help_text='pk2', max_length=100)),
                ('photo', models.ImageField(blank=True, default='default.jpg', help_text='Your Image', upload_to='')),
                ('post', models.TextField(help_text='Your post')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0, help_text='Likes')),
                ('comments', models.IntegerField(default=0, help_text='comments')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='', help_text='Your')),
                ('photo', models.ImageField(blank=True, default='default.jpg', help_text='Your Image', upload_to='')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('likes', models.BooleanField(default=False, help_text='Likess')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='', help_text='Your')),
                ('photo', models.ImageField(blank=True, default='default.jpg', help_text='Your Image', upload_to='')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(default='', help_text='comments')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('photo', models.ImageField(blank=True, help_text='An Image', upload_to='')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
