# Generated by Django 2.2.1 on 2019-06-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='userPhoto',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Your Image', upload_to=''),
        ),
    ]
