# Generated by Django 2.2.1 on 2019-06-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190606_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_no',
            field=models.CharField(default='', help_text='Your student number', max_length=20),
        ),
    ]
