# Generated by Django 2.2.1 on 2019-06-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_profile_student_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', help_text='This will be your profile picture', upload_to=''),
        ),
    ]
