# Generated by Django 2.2.1 on 2019-06-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, help_text='An Image', upload_to=''),
        ),
    ]
