# Generated by Django 2.2.1 on 2019-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_comment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Your Image', upload_to=''),
        ),
    ]
