# Generated by Django 2.2.1 on 2019-06-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_posts_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comment',
            field=models.TextField(default='', help_text='comments'),
        ),
    ]
