# Generated by Django 2.2.1 on 2019-06-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20190610_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='post',
            field=models.TextField(default='', help_text='Your'),
        ),
    ]
