# Generated by Django 2.2.1 on 2019-06-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_postcomments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='comments',
            field=models.IntegerField(default=0, help_text='comments'),
        ),
        migrations.AddField(
            model_name='postcomments',
            name='likes',
            field=models.IntegerField(default=0, help_text='Likes'),
        ),
    ]
