# Generated by Django 2.2.1 on 2019-06-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20190610_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='postcomments',
            name='likes',
        ),
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.IntegerField(default=0, help_text='comments'),
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.IntegerField(default=0, help_text='Likes'),
        ),
    ]
